Paths:
  # Full paths to folders
  subj_seeg_path: "/mnt/ernie_main/000_Data/SEEG/SEEG_EyesClosed_RestingState/data/$SUBJ"
  subj_preproc_path: "/mnt/ernie_main/000_Data/SPES/data/preprocessed/$SUBJ"
  tb_logs_path: "/home/withercp/Documents/dev/SPES_Transformer/src/tb_logs"
  
  # Full paths to files
  soz_labels_fpath: "/mnt/ernie_main/000_Data/SEEG/SEEG_EyesClosed_RestingState/labels/all_pats_bipole_soz_labels.csv"

  # Folder names
  subj_pulse_dir: "$SUBJ_CCEP_single_pulses_bipole"
  subj_pretrain_dir: "$SUBJ_CCEP_pre_train_baselines"
  
  # File names
  subj_bip_lut_file: '$SUBJ_crave_edf_LUT.csv'
  subj_coords_file: '$SUBJ_coords_registered.csv'
  roi_assignments_file: 'SEEG_BipMontage_ROI_Assignments_EditedWithEEG.csv'
  mni_file: 'mni.nii'

Parameters:
  # Preprocessing
  dist_threshold: 20  # Minimum distance (in mm) between stim and recording electrodes for inclusion

  ## Training
  # Train
  batch_size: 6
  sz_free_only: false
  n_epochs: 15
  n_steps_per_update: 1
  patience: 3
  val_ratio: 0
  use_clipping: false
  clip_max_norm: 10.0   # only applies if clipping set to true

  # Model
  embed_dim: 192
  num_layers: 5
  n_heads: 4

  # Optimizer
  weight_decay: 0.0002012915968425392

  # Scheduler
  base_lr: 1.9947771573336754e-05
  max_lr: 8.774492933643487e-05
  pct_start: 0.4314841606163928