paths:
  # Full paths to folders
  subj_seeg_path: "/mnt/ernie_main/000_Data/SEEG/SEEG_EyesClosed_RestingState/data/$SUBJ"
  subj_preproc_path: "/mnt/ernie_main/000_Data/SPES/data/preprocessed/$SUBJ"
  tb_logs_path: "/home/withercp/Documents/dev/SPES_Transformer/src/tb_logs"
  
  # Full paths to files
  soz_labels_fpath: "/mnt/ernie_main/000_Data/SEEG/SEEG_EyesClosed_RestingState/labels/all_pats_bipole_soz_labels.csv"

  # Folder names
  subj_train_dir: "$SUBJ_CCEP_new_padded_full_trains"
  
  # File names
  subj_coords_file: '$SUBJ_coords_registered.csv'
  subj_bip_lut_file: '$SUBJ_crave_edf_LUT_cleaned.csv'
  roi_assignments_file: 'SEEG_BipMontage_ROI_Assignments_EditedWithEEG_cleaned.csv'
  mni_file: 'mni.nii'

parameters:
  ## Preprocessing
  dist_threshold: 15  # Minimum distance (in mm) between stim and recording electrodes for inclusion
  tol_ms: 50  # maximum tolerance for SPES peak detection
  artifact_pad_ms: 15.0 # padding in ms to add before and after each pulse for artifact removal
  zscore_baseline_end_s: 2.5 # length in s of time period to z-score pulses based on

  ## Training
  # Train
  batch_size: 6
  sz_free_only: false
  n_epochs: 6
  n_steps_per_update: 1
  patience: 6
  min_epochs: 0
  val_ratio: 0
  use_clipping: false
  clip_max_norm: 10.0   # only applies if clipping set to true
  random_seed: 1

  # Model
  embed_dim: 256
  num_layers: 2
  n_heads: 8

  # Optimizer
  weight_decay: 4.2736128332696716e-05

  # Scheduler
  base_lr: 1.1524771622578236e-06
  max_lr: 5.355298326119835e-05
  pct_start: 0.4381293521209439