paths:
  # Full paths to folders
  subj_seeg_path: "/mnt/ernie_main/000_Data/SEEG/SEEG_EyesClosed_RestingState/data/$SUBJ"
  subj_preproc_path: "/mnt/ernie_main/000_Data/SPES/data/preprocessed/$SUBJ"
  tb_logs_path: "/home/withercp/Documents/dev/SPES_Transformer/src/tb_logs"
  
  # Full paths to files
  soz_labels_fpath: "/mnt/ernie_main/000_Data/SEEG/SEEG_EyesClosed_RestingState/labels/all_pats_bipole_soz_labels.csv"

  # Folder names
  subj_train_dir: "$SUBJ_CCEP_new_padded_full_trains"
  
  # File names
  subj_coords_file: '$SUBJ_coords_registered.csv'
  subj_bip_lut_file: '$SUBJ_crave_edf_LUT_cleaned.csv'
  roi_assignments_file: 'SEEG_BipMontage_ROI_Assignments_EditedWithEEG_cleaned.csv'
  mni_file: 'mni.nii'

parameters:
  ## Preprocessing
  dist_threshold: 15  # Minimum distance (in mm) between stim and recording electrodes for inclusion
  tol_ms: 50  # maximum tolerance for SPES peak detection
  artifact_pad_ms: 15.0 # padding in ms to add before and after each pulse for artifact removal
  zscore_baseline_end_s: 2.5 # length in s of time period to z-score pulses based on

  ## Training
  # General
  batch_size: 6
  n_steps_per_update: 1
  n_epochs: 1
  patience: 3
  n_folds: 5
  sz_free_only: false
  use_clipping: false
  clip_max_norm: 10.0   # only applies if clipping set to true
  random_seed: 1
  n_hp_searches: 1

  # Hyperparameter search spaces
  search:
    embed_dim:
      type: int
      low: 128
      high: 320
      step: 32

    num_layers:
      type: int
      low: 2
      high: 6

    n_heads:
      type: categorical
      choices: [2, 4, 8]

    weight_decay:
      type: loguniform
      low: 1.0e-5
      high: 1.0e-3

    base_lr:
      type: loguniform
      low: 1.0e-7
      high: 3.0e-4

    max_lr:
      type: loguniform
      high: 5.0e-3

    pct_start:
      type: uniform
      low: 0.05
      high: 0.55