Paths:
  # Full paths to folders
  subj_seeg_path: "/mnt/ernie_main/000_Data/SEEG/SEEG_EyesClosed_RestingState/data/$SUBJ"
  subj_preproc_path: "/mnt/ernie_main/000_Data/SPES/data/preprocessed/$SUBJ"
  
  # Full paths to files
  soz_labels_fpath: "/mnt/ernie_main/000_Data/SEEG/SEEG_EyesClosed_RestingState/labels/all_pats_bipole_soz_labels.csv"

  # Folder names
  subj_pulse_dir: "$SUBJ_CCEP_new_single_pulses_bipole"
  
  # File names
  subj_bip_lut_file: '$SUBJ_crave_edf_LUT.csv'
  subj_coords_file: '$SUBJ_coords_registered.csv'
  roi_assignments_file: 'SEEG_BipMontage_ROI_Assignments_EditedWithEEG.csv'
  mni_file: 'mni.nii'

Parameters:

