Paths:
  # Full paths to folders
  subj_seeg_path: "/mnt/ernie_main/000_Data/SEEG/SEEG_EyesClosed_RestingState/data/$SUBJ"
  subj_preproc_path: "/mnt/ernie_main/000_Data/SPES/data/preprocessed/$SUBJ"
  tb_logs_path: "/home/withercp/Documents/dev/SPES_Transformer/src/tb_logs"
  
  # Full paths to files
  soz_labels_fpath: "/mnt/ernie_main/000_Data/SEEG/SEEG_EyesClosed_RestingState/labels/all_pats_bipole_soz_labels.csv"

  # Folder names
  subj_pulse_dir: "$SUBJ_CCEP_single_pulses_bipole"
  subj_pretrain_dir: "$SUBJ_CCEP_pre_train_baselines"
  
  # File names
  subj_bip_lut_file: '$SUBJ_crave_edf_LUT.csv'
  subj_coords_file: '$SUBJ_coords_registered.csv'
  roi_assignments_file: 'SEEG_BipMontage_ROI_Assignments_EditedWithEEG.csv'
  mni_file: 'mni.nii'

Parameters:
  # Preprocessing
  dist_threshold: 20  # Minimum distance (in mm) between stim and recording electrodes for inclusion

  # Training
  batch_size: 8
  sz_free_only: false
  n_epochs: 30
  n_steps_per_update: 1
  patience: 5
  val_ratio: 0.2
  base_lr: 0.00001
  max_lr: 0.0001
  step_size_up_down: 1000
  weight_decay: 0.0001
  embed_dim: 128
  pct_start: 0.2
  num_layers: 4
